[package]
name = "create-window"
version = "0.0.0"
edition = "2018"

[dependencies.windows-sys]
version = "0.27"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
    "Win32_UI_WindowsAndMessaging",
]
