[package]
name = "bindings"
version = "0.0.0"
edition = "2018"

[dependencies]
windows = { version = "0.27", features = ["build"] }

[build-dependencies]
windows = { version = "0.27", features = ["build"] }
